In [1]:
import torch
import torch.nn as nn
import os
import torch.utils.data as data
#GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))
#損失関数
criterion = nn.CrossEntropyLoss()


Using cuda device


# 今日は試しに学習させてみる


In [2]:
model = torch.hub.load('torchvggish-master', 'vggish', source='local').to(device)
#harritaylor/
#model.eval()
'''
# Download an example audio file
import urllib
url, filename = ("http://soundbible.com/grab.php?id=1698&type=wav", "bus_chatter.wav")
try: urllib.URLopener().retrieve(url, filename)
except: urllib.request.urlretrieve(url, filename)

model.forward(filename)```'''

vggish/embedding:0


'\n# Download an example audio file\nimport urllib\nurl, filename = ("http://soundbible.com/grab.php?id=1698&type=wav", "bus_chatter.wav")\ntry: urllib.URLopener().retrieve(url, filename)\nexcept: urllib.request.urlretrieve(url, filename)\n\nmodel.forward(filename)```'

In [3]:
class MyClassfilter(nn.Module):
    def __init__(self):
        super(MyClassfilter, self).__init__()
        self.classfilter=nn.Sequential(
            nn.Linear(128,64),
            nn.Sigmoid(),
            nn.Linear(64,5),
            nn.Softmax()
        )
    def forward(self, x):
        return self.classfilter(x)
mymodel = MyClassfilter().to(device)
mymodel.eval()

MyClassfilter(
  (classfilter): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=64, out_features=5, bias=True)
    (3): Softmax(dim=None)
  )
)

In [4]:
# 学習済みの重みを使用
use_pretrained = True

# モデルをロード
print(model)

VGGish(
  (features): Sequential(
    (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (11): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): ReLU(inplace=True)
    (13): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (14): ReLU(inplace=True)
    (15): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False

In [5]:
#print('変更前 : ', model.embeddings[4])
#model.embeddings[4] = nn.Linear(in_features=4096, out_features=5)
#print('変更あと : ', model.embeddings[4])

In [6]:
#model.classfilter=nn.Sequential(
#    nn.Linear(128, 5)   
#)
#print(model)

In [7]:
#試しに実行
#model.eval()# 評価しない
import urllib
url, filename = ("http://soundbible.com/grab.php?id=1698&type=wav", "bus_chatter.wav")
try: urllib.URLopener().retrieve(url, filename)
except: urllib.request.urlretrieve(url, filename)
#a =model.forward(filename)
#rint(a.size(),a.dim())
#print(mymodel.forward(a))

In [8]:
#データセットの定義？
classes=["Speech","Wind","Animal","Music","Speech"]
dataset_dir="C:/Users/hase/git/youtubedl/result"


def make_path_list():
    train_file_list=[]
    valid_file_list=[]
    for i in range(len(classes)):
        dir_name=os.path.join(dataset_dir,classes[i]).replace("\\","/")
        file_list=os.listdir(dir_name)
        
        #8割を学習用、残りを検証用にする
        num_data = len(file_list)
        num_split = int(num_data*0.8)
        
        train_file_list += [[os.path.join(dir_name, file).replace('\\', '/'), i] for file in file_list[:num_split] ]
        valid_file_list += [[os.path.join(dir_name, file).replace('\\', '/'), i] for file in file_list[num_split:]]
    return {"train":train_file_list,"valid":valid_file_list}
# 画像データへのファイルパスとラベルを格納したリストを取得する
data_dict = make_path_list()
## リストが変かもなのでみてみる


print('学習データ数 : ', len(data_dict["train"]))
##### 先頭3件だけ表示
print(data_dict["train"][:3])

print('検証データ数 : ', len(data_dict["valid"]))
##### 先頭3件だけ表示
print(data_dict["valid"][:3])

学習データ数 :  162
[['C:/Users/hase/git/youtubedl/result/Speech/--aE2O5G5WE.wav', 0], ['C:/Users/hase/git/youtubedl/result/Speech/--PJHxphWEs.wav', 0], ['C:/Users/hase/git/youtubedl/result/Speech/-30H9V1IKps.wav', 0]]
検証データ数 :  44
[['C:/Users/hase/git/youtubedl/result/Speech/-L44JqysUy8.wav', 0], ['C:/Users/hase/git/youtubedl/result/Speech/-L68XDzhn2g.wav', 0], ['C:/Users/hase/git/youtubedl/result/Speech/-LBl0UeKNyU.wav', 0]]


In [9]:
#0830
#DataSet型を作る必要がある気がする
class MyDataset(data.Dataset):
    '''
    data_dictは[パス,番号]
    '''
    def __init__(self, data_dict,  phase='train'):
        self.data_dict = data_dict
        self.phase = phase
        
    def __len__(self):
        return len(self.data_dict)
    
    def __getitem__(self,index):
        
        wav_path,label = self.data_dict[index]
        
        return wav_path, label

#DataSetを実際に作ってみる 

train_dataset = MyDataset(
    data_dict=data_dict["train"],
    phase="train"
)

valid_dataset = MyDataset(
    data_dict=data_dict["valid"],
    phase="valid"
)

#test
print(train_dataset.__getitem__(0))


('C:/Users/hase/git/youtubedl/result/Speech/--aE2O5G5WE.wav', 0)


In [10]:
#0830
#もう1手ひつようらしい

#dataloaderを用いてミニバッチを作成
batch_size=10

train_dataloader=data.DataLoader(
    train_dataset, batch_size = batch_size, shuffle=True
)
valid_dataloader=data.DataLoader(
    valid_dataset, batch_size = batch_size//2, shuffle=True
)

dataloader_dict={
    'train': train_dataloader, 
    'valid': valid_dataloader
}
print(dataloader_dict)

{'train': <torch.utils.data.dataloader.DataLoader object at 0x000001D00467C460>, 'valid': <torch.utils.data.dataloader.DataLoader object at 0x000001D00467C5E0>}


In [11]:
# パラメータ名の確認
for name, param in model.named_parameters():
    print('name : ', name)
for prm in mymodel.named_parameters():
    print(prm)
#print(mymodel.parameters())

name :  features.0.weight
name :  features.0.bias
name :  features.3.weight
name :  features.3.bias
name :  features.6.weight
name :  features.6.bias
name :  features.8.weight
name :  features.8.bias
name :  features.11.weight
name :  features.11.bias
name :  features.13.weight
name :  features.13.bias
name :  embeddings.0.weight
name :  embeddings.0.bias
name :  embeddings.2.weight
name :  embeddings.2.bias
name :  embeddings.4.weight
name :  embeddings.4.bias
name :  pproc.pca_eigen_vectors
name :  pproc.pca_means
('classfilter.0.weight', Parameter containing:
tensor([[ 0.0415, -0.0314,  0.0773,  ...,  0.0744, -0.0014,  0.0186],
        [ 0.0200,  0.0314,  0.0122,  ..., -0.0118,  0.0340,  0.0601],
        [ 0.0310,  0.0439, -0.0441,  ..., -0.0067,  0.0132,  0.0759],
        ...,
        [ 0.0849,  0.0634, -0.0015,  ..., -0.0235, -0.0794, -0.0627],
        [-0.0866, -0.0532, -0.0156,  ..., -0.0122, -0.0631, -0.0340],
        [-0.0394,  0.0767, -0.0270,  ...,  0.0336,  0.0545, -0.0727]

In [12]:
#学習させるパラメータを格納
params_to_update=[]
#学習させるパラメータ名
update_param_names=['classfilter.0.weight', 'classfilter.0.bias', 'classfilter.2.weight']

#対象以外は購買計算をせず、変化しないようにもする
for name,param in mymodel.named_parameters():
    if name in update_param_names:
        param.requires_grad = True
        params_to_update.append(param)
        print("name : ",name)
    else:
        param.requires_grad = False


name :  classfilter.0.weight
name :  classfilter.0.bias
name :  classfilter.2.weight


In [13]:
import torch.optim as optim
#optimizer = optim.SGD(params_to_update, lr=0.01)
optimizer = optim.SGD(params_to_update, lr=0.01)

In [25]:
#エポック数
num_epochs=20

for epoch in range(num_epochs):
    print('Epoch {}/{}'.format(epoch+1,num_epochs))
    
    for phase in ['train','valid']:
        if phase == 'train':
            mymodel.train()#学習モード
        else:
            mymodel.eval()#検証？
    
        #epoch全体の損失の輪と正解数
        epoch_loss=0.0
        epoch_corrects=0
        
        count=0.0
        #print(phase)
        for inputs, labels in dataloader_dict[phase]:
            #入力の確認
            #print(len(inputs),len(labels))
            #optimizer?を初期化?する?
            optimizer.zero_grad()
            print(len(inputs))
            output_models=[]
            output_labels=[]
            with torch.set_grad_enabled(phase=='train'):

                #outputs=mymodel(torch.tensor([model(input).tolist()[0] for input in inputs]).to(device))
               #0906 これ([0])はあかんやろってなった
                for i, label in zip(inputs, labels):
                    out1=model(i)
                    output=mymodel(out1)
                    #print(output)
                    for h in output:
                       # print(h.tolist())
                        output_models.append(h.tolist())
                        #output_models.append(h)
                        output_labels.append(label.tolist())
                        count+=1
                        #print(label)
                
                output_models=torch.tensor(output_models, device=device, grad_fn=output.grad_fn)
                output_labels=torch.tensor(output_labels, device=device)
               # labels=labels.to(device)
                #print(output_models)
                loss=criterion(output_models, output_labels)
                
                #ラベルを予測
                _,preds = torch.max(output_models,1)
                
                #訓練時は逆伝搬の計算
                if phase == "train":
                    #逆伝搬
                    loss.backward()
                    
                    #パラメータ更新
                    optimizer.step()
                
                #イテレーション結果の計算
                #lossの合計を更新
                #pytorchの使用上バッチ内の平均lossが計算されているのでデータ数をかけて合計にする
                #損失和を「全データの損失/データ数」で求めるせいらしい?
                #print(len(inputs))
                #epoch_loss += loss.item() * inputs.size(0)
                epoch_loss += loss.item()*output_labels.size(0)
                
                #正解数の合計を更新
                #epoch_corrects += torch.sum(preds == labels.data)
                #print(preds.size(),count,output_labels.size(0))
                #print()
                epoch_corrects += torch.sum(preds == output_labels)
        #epochのlossと正解数の表示
        #epoch_loss=epoch_loss/len(dataloader_dict[phase])
        #epoch_acc=epoch_corrects.double()/len(dataloader_dict[phase].dataset)
        #print(epoch_loss, epoch_corrects.double(), count)
        epoch_loss=epoch_loss/count
        epoch_acc=epoch_corrects.double()/count
        print('{} Loss: {:.4f} Acc: {:.4f}'.format(phase, epoch_loss, epoch_acc))
        
    

Epoch 1/20
10


C:\Users\hase\anaconda3\lib\site-packages\torch\nn\modules\container.py:119: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


TypeError: tensor() got an unexpected keyword argument 'grad_fn'

In [ ]:









m = nn.Softmax(dim=2)
input = torch.randn(4, 4)
output = m(input)
print(input)
print(output)

In [ ]:
m = nn.Sigmoid()
input = torch.randn(2)
output = m(input)
print(input,output)

In [ ]:
model.forward("C:/Users/hase/git/youtubedl/result/Speech/--aE2O5G5WE.wav")

In [19]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

output = loss(input, target)
output.backward()
print(input,target,output, sep='\n')
print(output.grad_fn)

tensor([[ 0.7255,  0.1400, -0.2283,  2.8252, -2.2803],
        [ 1.2004,  0.8045,  1.0707,  1.0409,  1.2993],
        [ 1.4840,  0.0255,  0.0423,  0.6021,  1.4970]], requires_grad=True)
tensor([2, 2, 1])
tensor(2.4764, grad_fn=<NllLossBackward>)


In [22]:
a=torch.tensor([])
a

tensor([])

In [23]:
a.append([1])

AttributeError: 'Tensor' object has no attribute 'append'